# Generated by Django 3.0.5 on 2020-06-24 20:25

import Items.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0006_auto_20200623_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='picture',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=Items.models.upload_image_path)),
                ('item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Items.Item')),
            ],
        ),
    ]
